import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import MainBackground from "@/components/MainBackground";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const inter = Inter({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: {
    template: "%s | Crazy Game from Xitrumvndn",
    default: "Crazy Game from Xitrumvndn",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} ${geistSans.variable} ${geistMono.variable} antialiased text-[rgb(210,240,240)]`}
      >
        <div className="relative flex flex-col items-center h-screen bg-scroll">
          <MainBackground />
          <Navbar />
          <div className="h-screen w-full fixed bg-fixed bg-slate-900 z-[-1] opacity-30"></div>
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
