import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import "./globals.css";
import Image from "next/image";
import main_background from "@/public/images/main-background.webp";
import Navbar from "@/components/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const inter = Inter({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: {
    template: "%s | Crazy Game from Xitrumvndn",
    default: "Crazy Game from Xitrumvndn",
  },
  description: "Generated by create next app",
};

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} ${geistSans.variable} ${geistMono.variable} antialiased text-slate-300`}
      >
        <div className="relative h-screen bg-scroll">
          <Image
            src={main_background}
            alt="Main background"
            layout="fill"
            objectFit="cover"
            quality={100}
            className="z-[-2]"
          />
          <Navbar />
          <div className="h-full w-full bg-fixed bg-slate-900 z-[-1] opacity-30 absolute"></div>
          {/* <Home /> */}

          {children}
        </div>
        <footer>Footer here!</footer>
      </body>
    </html>
  );
}
